title: ICA Status Page
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: Assistants
      description: "Assistant Library Health "
      link: ""
    - name: User Management
      description: "All Logins "
      link: ""
    - name: Document Collections
      description: ICA Document Collections
    - name: "Chats "
      description: ICA Chat Bots
    - name: "Launch Pad "
      description: https://servicesessentials.ibm.com/launchpad
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: " UTC"
  logo: /images/clearstatus.svg
  description_header: <a class='text-grey-darkest' title='Visit ICA homepage'
    href='https://servicesessentials.ibm.com/launchpad'>ICA LaunchPad</a>
  copyrightHolder: IBM
  eventsPerPage: 10
  iconType: image/png
  groups:
    - UKI
  icon: /images/clearstatus.png
  description_footer: <a class='text-grey-darkest' title='Visit ICA homepage'
    href='https://servicesessentials.ibm.com/launchpad'>ICA LaunchPad</a>
    provides All assistants and Document collections About anything and
    Everything.
